# ============================================================================
# KSP MacroPad — LED state constants (CircuitPython)
# Mirrors mod/KSPMacropad/LEDStates.cs — values must stay in sync with it.
# ============================================================================
# NOTE: LEDStates.cs's own per-group comments are stale (reference an old
# macro-key layout). The groupings below use the CURRENT final macro list
# (see project doc's macro table) — the byte VALUES are unchanged from the
# .cs file, only these comments are corrected.

class LEDStates:
    # 0x00 - LAUNCH SEQUENCE
    LAUNCH_IDLE = 0x00
    LAUNCH_EXECUTING = 0x01
    LAUNCH_COMPLETE = 0x02

    # 0x01 - AUTO GRAVITY TURN (AGT)
    AGT_IDLE = 0x00
    AGT_ACTIVE = 0x01

    # 0x02 - CIRCULARIZE SETUP (CIRC)
    CIRC_IDLE = 0x00
    CIRC_UNAVAILABLE = 0x01
    CIRC_CALCULATING = 0x02
    CIRC_WARPING = 0x03
    CIRC_COMPLETE = 0x04

    # 0x03 - TIME ACCEL TO NEXT EVENT
    TIMEACCEL_IDLE = 0x00
    TIMEACCEL_UNAVAILABLE = 0x01
    TIMEACCEL_WARPING = 0x02

    # 0x04 - INTERCEPT CALC
    INTERCEPT_IDLE = 0x00
    INTERCEPT_CALCULATING = 0x01
    INTERCEPT_SOLUTION = 0x02
    INTERCEPT_INSUFFICIENT_DV = 0x03

    # 0x05 - ORBIT SYNC (ORBSYNC)
    ORBSYNC_IDLE = 0x00
    ORBSYNC_CALCULATING = 0x01
    ORBSYNC_EXECUTING = 0x02
    ORBSYNC_COMPLETE = 0x03

    # 0x06 - RENDEZVOUS PREP
    RENDEZVOUS_IDLE = 0x00
    RENDEZVOUS_ACTIVE = 0x01
    RENDEZVOUS_IN_RANGE = 0x02

    # 0x07 - DEORBIT BURN
    DEORBIT_IDLE = 0x00
    DEORBIT_UNAVAILABLE = 0x01
    DEORBIT_PLANNED = 0x02
    DEORBIT_WARPING = 0x03
    DEORBIT_BURNING = 0x04

    # 0x08 - DOCKING PREP (DOCK)
    DOCK_IDLE = 0x00
    DOCK_ACTIVE = 0x01
    DOCK_TARGET_ACQUIRED = 0x02
    DOCK_READY = 0x03

    # 0x09 - LANDING PREP
    LANDING_IDLE = 0x00
    LANDING_CONFIGURING = 0x01
    LANDING_COMPLETE = 0x02

    # 0x0A - SUICIDE BURN ARM
    SUICIDEBURN_IDLE = 0x00
    SUICIDEBURN_ARMED = 0x01
    SUICIDEBURN_IMMINENT = 0x02
    SUICIDEBURN_BURNING = 0x03

    # 0x0B - PRECISION INPUT TOGGLE: onboard-only, no LED states

    # 0x0C - TRANSMIT SCIENCE (SCIENCE)
    SCIENCE_IDLE = 0x00
    SCIENCE_UNAVAILABLE = 0x01
    SCIENCE_TRANSMITTING = 0x02
    SCIENCE_COMPLETE = 0x03

    # 0x0D - RESOURCE MONITOR MODE (RESOURCE)
    RESOURCE_IDLE = 0x00
    RESOURCE_NOMINAL = 0x01
    RESOURCE_LOW = 0x02
    RESOURCE_VERYLOW = 0x03
    RESOURCE_CRITICAL = 0x04
    RESOURCE_DEPLETING = 0x05

    # 0x0E - AUX MODE TOGGLE: onboard-only, no LED states

    # 0x0F - AUTOPILOT
    AUTOPILOT_IDLE = 0x00
    AUTOPILOT_IMPOSSIBLE = 0x01
    AUTOPILOT_READY = 0x02
    AUTOPILOT_PLANNING = 0x03
    AUTOPILOT_EXECUTING = 0x04

    # 0x10-0x13 - UNDERGLOW (all 4 zones share this one group)
    UNDERGLOW_IDLE = 0x00
    UNDERGLOW_CONNECTED_NOVESSEL = 0x01
    UNDERGLOW_LAUNCHPAD = 0x02
    UNDERGLOW_ASCENT = 0x03
    UNDERGLOW_STABLE_ORBIT = 0x04
    UNDERGLOW_TIMEWARP = 0x05
    UNDERGLOW_MANEUVER_IMMINENT = 0x06
    UNDERGLOW_LANDING = 0x07
    UNDERGLOW_AUTOPILOT = 0x08
    UNDERGLOW_CRITICAL_RESOURCE = 0x09
    UNDERGLOW_COMMS_LOST = 0x0A